### ISSUE TITLE
Creating a new survey causes a backtrace

### ISSUE THREAD

**Issue by benzea** [sdaps/sdaps_web#10]
Currently, creating a new survey causes a backtrace. Probably a pretty simple bug somewhere.

```
[2018-11-05 21:51:02,639: ERROR/ForkPoolWorker-1] Task sdaps_ctl.tasks.render_questionnaire[651aaed0-23c4-4e86-b823-90285b974937] raised unexpected: ValueError("invalid literal for int() with base 10: '<django.db.models.query_utils.DeferredAttribute object at 0x7fdf23ca9128>'",)
Traceback (most recent call last):
  File "/home/benjamin/.local/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/benjamin/.local/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/benjamin/sdaps_web/sdaps_ctl/tasks.py", line 197, in render_questionnaire
    djsurvey = get_object_or_404(models.Survey, pk=djsurvey_id)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 787, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 805, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/usr/lib/python3/dist-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/lib/python3/dist-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/lib/python3/dist-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '<django.db.models.query_utils.DeferredAttribute object at 0x7fdf23ca9128>'
```

**Comment by TheRadialActive** [comment]
This may be fixed by 0d163f4b71e4e16e7ff0b06e5fbbdebeac460d48.
